"""Population self-play: a library of frozen policies, randomised games, and a
scenario mixture that starts some hands on later streets.

Three ideas, each addressing a weakness the trajectory experiment exposed:

* **A policy library.**  Every hand seats the learner once and fills the other
  two seats from a library of frozen checkpoints.  Facing a *distribution* of
  past selves, rather than only the current self, is what damps the strategy-
  cycling that made single-checkpoint strength oscillate.

* **Randomised full games.**  Each game starts from random stacks and a random
  blind level and is played from the button's first action to showdown -- not
  resumed from a synthetic table state.  The agent sees the full range of stack
  depths, not just one.

* **A scenario mixture.**  Most hands begin preflop, but a configurable minority
  have the learner *enter* on the flop, turn or river.  The earlier streets are
  still played out by the population, so the state the learner inherits has a
  realistic pot, board and opponent range -- it is generated by policies, not
  sampled uniformly.  This concentrates experience on later-street decisions,
  which are rare in complete-hand self-play (only a fraction of hands reach the
  river).
"""

from __future__ import annotations

import copy
import random
from dataclasses import dataclass
from typing import List, Optional

from paradigm_a.config import Config
from paradigm_a.environment.state import NUM_BETTING_STREETS, Street

# --- policy library --------------------------------------------------------
class PolicyLibrary:
    """A capacity-bounded, recency-weighted collection of frozen policies.

    Entries are ordered oldest -> newest.  Sampling weight increases with
    recency; ``linear`` gives the newest of ``K`` retained policies weight ``K``
    and the oldest weight ``1`` (a straight-line decline), while ``geometric``
    uses ``decay ** age``.
    """

    def __init__(
        self,
        capacity: int = 20,
        weighting: str = "linear",
        decay: float = 0.5,
    ) -> None:
        if weighting not in ("linear", "geometric"):
            raise ValueError(f"unknown weighting: {weighting!r}")
        self.capacity = max(1, int(capacity))
        self.weighting = weighting
        self.decay = decay
        self._policies: List = []

    def __len__(self) -> int:
        return len(self._policies)

    @property
    def is_empty(self) -> bool:
        return not self._policies

    def add(self, policy) -> None:
        """Append the newest policy, evicting the oldest past capacity."""
        self._policies.append(policy)
        if len(self._policies) > self.capacity:
            self._policies = self._policies[-self.capacity :]

    def weights(self) -> List[float]:
        k = len(self._policies)
        if self.weighting == "linear":
            # index 0 = oldest -> weight 1; index k-1 = newest -> weight k.
            return [float(i + 1) for i in range(k)]
        # geometric: age 0 = newest.
        return [self.decay ** (k - 1 - i) for i in range(k)]

    def sample(self, rng: random.Random):
        """One policy, recency-weighted."""
        if self.is_empty:
            raise ValueError("cannot sample from an empty library")
        return rng.choices(self._policies, weights=self.weights(), k=1)[0]

    def sample_many(self, n: int, rng: random.Random) -> List:
        """``n`` policies sampled independently (with replacement)."""
        return [self.sample(rng) for _ in range(n)]


# --- randomised game setup -------------------------------------------------
@dataclass
class GameSetup:
    dealer: int
    stacks: List[int]
    small_blind: int
    big_blind: int


def sample_game_setup(rng: random.Random, cfg: Config) -> GameSetup:
    """Random button, blind level and per-seat stack depths.

    Stacks are drawn independently per seat in big blinds, so uneven stacks --
    and therefore side pots and all-in spots -- arise naturally.
    """
    env, train = cfg.env, cfg.train
    n = env.num_players
    dealer = rng.randrange(n)

    if not train.population_random_setup:
        return GameSetup(
            dealer=dealer,
            stacks=[env.starting_stack] * n,
            small_blind=env.small_blind,
            big_blind=env.big_blind,
        )

    big_blind = int(rng.choice(list(train.population_big_blind_choices)))
    small_blind = max(1, big_blind // 2)
    lo, hi = train.population_stack_min_bb, train.population_stack_max_bb
    stacks = [int(round(rng.uniform(lo, hi) * big_blind)) for _ in range(n)]
    # A stack must at least cover the big blind, or the seat is all-in blind.
    stacks = [max(big_blind, stack) for stack in stacks]
    return GameSetup(dealer=dealer, stacks=stacks, small_blind=small_blind, big_blind=big_blind)


# --- scenario mixture ------------------------------------------------------
_ENTRY_STREETS = (Street.PREFLOP, Street.FLOP, Street.TURN, Street.RIVER)


def sample_entry_street(rng: random.Random, cfg: Config) -> Street:
    """Sample the street on which the learner takes over its seat."""
    probs = list(cfg.train.entry_street_probs)[:NUM_BETTING_STREETS]
    total = sum(probs)
    if total <= 0:
        return Street.PREFLOP
    probs = [p / total for p in probs]
    return rng.choices(_ENTRY_STREETS, weights=probs, k=1)[0]


# --- snapshotting ----------------------------------------------------------
def freeze_policy(cfg: Config, network, device: Optional[str] = None):
    """A frozen :class:`NetworkAgent` wrapping a copy of ``network``.

    Imported lazily to avoid a circular import with ``training.self_play``.
    """
    from paradigm_a.model.network import build_network
    from paradigm_a.training.self_play import NetworkAgent
    from paradigm_a.config import reward_scale

    frozen = build_network(cfg)
    frozen.load_state_dict(copy.deepcopy(network.state_dict()))
    frozen.eval()
    for parameter in frozen.parameters():
        parameter.requires_grad_(False)
    if device:
        frozen.to(device)
    agent = NetworkAgent(
        frozen,
        alpha=cfg.train.alpha,
        beta=cfg.train.beta,
        temperature=cfg.train.sampling_temperature,
        device=device,
        q_scale=reward_scale(cfg.env),
    )
    agent.name = "population"
    return agent
