"""Population self-play: a library of frozen policies, randomised games, and a
scenario mixture that starts some hands on later streets.

Three ideas, each addressing a weakness the trajectory experiment exposed:

* **A policy library.**  Every hand seats the learner once and fills the other
  two seats from a library of frozen checkpoints.  Facing a *distribution* of
  past selves, rather than only the current self, is what damps the strategy-
  cycling that made single-checkpoint strength oscillate.

* **Randomised full games.**  Each game starts from random stacks and a random
  blind level and is played from the button's first action to showdown -- not
  resumed from a synthetic table state.  The agent sees the full range of stack
  depths, not just one.

* **A scenario mixture.**  Most hands begin preflop, but a configurable minority
  have the learner *enter* on the flop, turn or river.  The earlier streets are
  still played out by the population, so the state the learner inherits has a
  realistic pot, board and opponent range -- it is generated by policies, not
  sampled uniformly.  This concentrates experience on later-street decisions,
  which are rare in complete-hand self-play (only a fraction of hands reach the
  river).
"""

from __future__ import annotations

import copy
import random
from dataclasses import dataclass
from typing import List, Optional

from config import Config, model_config
from environment.state import NUM_BETTING_STREETS, Street


# --- heterogeneous population ----------------------------------------------
#: Distinct "player types" for a heterogeneous co-evolving population.  Each is
#: (model preset, alpha, sampling_temperature, reward_mode); beta and everything
#: else come from the base config.  Diversity runs along capacity
#: (tiny/medium/large), improvement sharpness (alpha) and exploration
#: (temperature).  Members k cycle through this menu, so five members get one of
#: each.  All share the base obs and action layout, so they interoperate.
#:
#: Every archetype optimises the *same* objective (``normalized_chip_return``).
#: Mixing in ``binary`` (win-rate) members was measured and is a net negative:
#: in co-evolution each member is also everyone else's opponent, so members that
#: are deliberately bad at chip-EV poison the training distribution for the rest
#: -- the chip-EV members decayed from ~-40 to ~-400 bb/100 while the win-rate
#: members hit 0.83 win rate.  Diversity only helps when it raises opponent
#: quality; differ in style, not in what you optimise.
POPULATION_ARCHETYPES = (
    ("medium", 0.05, 0.40, "normalized_chip_return"),  # tuned default
    ("large", 0.05, 0.40, "normalized_chip_return"),   # high capacity
    ("tiny", 0.10, 0.70, "normalized_chip_return"),    # small, loose, exploratory
    ("medium", 0.03, 0.30, "normalized_chip_return"),  # sharp exploiter
    ("tiny", 0.08, 0.55, "normalized_chip_return"),    # small, mid-exploratory
)


def build_population_configs(base: Config, n: int) -> List[Config]:
    """One :class:`Config` per co-evolving member.

    Homogeneous (the default) returns the base config for every member -- five
    clones, unchanged behaviour.  When ``base.train.heterogeneous_population`` is
    set, member ``k`` takes archetype ``k % len(POPULATION_ARCHETYPES)``: its own
    network size, alpha, temperature and reward mode, with the observation and
    action layout (and the rest of the config) inherited from ``base`` so the
    members remain interoperable.
    """
    if not base.train.heterogeneous_population:
        return [base] * n
    configs: List[Config] = []
    for k in range(n):
        preset, alpha, temperature, reward_mode = POPULATION_ARCHETYPES[k % len(POPULATION_ARCHETYPES)]
        cfg = Config.from_dict(base.to_dict())  # deep copy
        cfg.model = model_config(preset)
        cfg.train.alpha = alpha
        cfg.train.sampling_temperature = temperature
        cfg.env.reward_mode = reward_mode
        configs.append(cfg)
    return configs

# --- policy library --------------------------------------------------------
class PolicyLibrary:
    """A capacity-bounded, recency-weighted collection of frozen policies.

    Entries are ordered oldest -> newest.  Sampling weight increases with
    recency; ``linear`` gives the newest of ``K`` retained policies weight ``K``
    and the oldest weight ``1`` (a straight-line decline), while ``geometric``
    uses ``decay ** age``.
    """

    def __init__(
        self,
        capacity: int = 20,
        weighting: str = "linear",
        decay: float = 0.5,
    ) -> None:
        if weighting not in ("linear", "geometric"):
            raise ValueError(f"unknown weighting: {weighting!r}")
        self.capacity = max(1, int(capacity))
        self.weighting = weighting
        self.decay = decay
        self._policies: List = []

    def __len__(self) -> int:
        return len(self._policies)

    @property
    def is_empty(self) -> bool:
        return not self._policies

    def add(self, policy) -> None:
        """Append the newest policy, evicting the oldest past capacity."""
        self._policies.append(policy)
        if len(self._policies) > self.capacity:
            self._policies = self._policies[-self.capacity :]

    def weights(self) -> List[float]:
        k = len(self._policies)
        if self.weighting == "linear":
            # index 0 = oldest -> weight 1; index k-1 = newest -> weight k.
            return [float(i + 1) for i in range(k)]
        # geometric: age 0 = newest.
        return [self.decay ** (k - 1 - i) for i in range(k)]

    def sample(self, rng: random.Random):
        """One policy, recency-weighted."""
        if self.is_empty:
            raise ValueError("cannot sample from an empty library")
        return rng.choices(self._policies, weights=self.weights(), k=1)[0]

    def sample_many(self, n: int, rng: random.Random) -> List:
        """``n`` policies sampled independently (with replacement)."""
        return [self.sample(rng) for _ in range(n)]


# --- randomised game setup -------------------------------------------------
@dataclass
class GameSetup:
    dealer: int
    stacks: List[int]
    small_blind: int
    big_blind: int


def sample_game_setup(rng: random.Random, cfg: Config) -> GameSetup:
    """Random button, blind level and per-seat stack depths.

    Stacks are drawn independently per seat in big blinds, so uneven stacks --
    and therefore side pots and all-in spots -- arise naturally.
    """
    env, train = cfg.env, cfg.train
    n = env.num_players
    dealer = rng.randrange(n)

    if not train.population_random_setup:
        return GameSetup(
            dealer=dealer,
            stacks=[env.starting_stack] * n,
            small_blind=env.small_blind,
            big_blind=env.big_blind,
        )

    big_blind = int(rng.choice(list(train.population_big_blind_choices)))
    small_blind = max(1, big_blind // 2)
    lo, hi = train.population_stack_min_bb, train.population_stack_max_bb
    stacks = [int(round(rng.uniform(lo, hi) * big_blind)) for _ in range(n)]
    # A stack must at least cover the big blind, or the seat is all-in blind.
    stacks = [max(big_blind, stack) for stack in stacks]
    return GameSetup(dealer=dealer, stacks=stacks, small_blind=small_blind, big_blind=big_blind)


# --- scenario mixture ------------------------------------------------------
_ENTRY_STREETS = (Street.PREFLOP, Street.FLOP, Street.TURN, Street.RIVER)


def sample_entry_street(rng: random.Random, cfg: Config) -> Street:
    """Sample the street on which the learner takes over its seat."""
    probs = list(cfg.train.entry_street_probs)[:NUM_BETTING_STREETS]
    total = sum(probs)
    if total <= 0:
        return Street.PREFLOP
    probs = [p / total for p in probs]
    return rng.choices(_ENTRY_STREETS, weights=probs, k=1)[0]


# --- snapshotting ----------------------------------------------------------
def freeze_policy(cfg: Config, network, device: Optional[str] = None):
    """A frozen :class:`NetworkAgent` wrapping a copy of ``network``.

    Imported lazily to avoid a circular import with ``training.self_play``.
    """
    from model.network import build_network
    from training.self_play import NetworkAgent
    from config import reward_scale

    frozen = build_network(cfg)
    frozen.load_state_dict(copy.deepcopy(network.state_dict()))
    frozen.eval()
    for parameter in frozen.parameters():
        parameter.requires_grad_(False)
    if device:
        frozen.to(device)
    agent = NetworkAgent(
        frozen,
        alpha=cfg.train.alpha,
        beta=cfg.train.beta,
        temperature=cfg.train.sampling_temperature,
        device=device,
        q_scale=reward_scale(cfg.env),
    )
    agent.name = "population"
    return agent
